"""initial schema

Revision ID: 0a05738fa2d4
Revises: 
Create Date: 2026-07-31 02:12:46.994457
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# HAND-EDITED: autogenerate emitted pgvector.sqlalchemy.vector.VECTOR below without
# importing it. This is the known gap in autogenerate's handling of third-party
# column types — it renders the repr but not the import.
import pgvector.sqlalchemy

revision: str = '0a05738fa2d4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('low_evidence', sa.Boolean(), nullable=False),
    sa.CheckConstraint("source IN ('itachi9604', 'dhivyeshrk', 'both')", name='ck_disease_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_disease_slug'), 'disease', ['slug'], unique=True)
    op.create_table('red_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('require_all', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.CheckConstraint("level IN ('emergency', 'urgent')", name='ck_red_flag_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('severity_weight', sa.SmallInteger(), nullable=True),
    sa.Column('body_system', sa.String(length=30), nullable=True),
    sa.Column('idf', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.CheckConstraint('severity_weight IS NULL OR severity_weight BETWEEN 1 AND 7', name='ck_symptom_severity_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index(op.f('ix_symptom_body_system'), 'symptom', ['body_system'], unique=False)
    op.create_index('ix_symptom_name_trgm', 'symptom', ['canonical_name'], unique=False, postgresql_using='gin', postgresql_ops={'canonical_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_symptom_slug'), 'symptom', ['slug'], unique=True)
    # HAND-EDITED: autogenerate does not emit pgvector index types.
    op.create_index('ix_symptom_embedding_hnsw', 'symptom', ['embedding'],
                    unique=False, postgresql_using='hnsw',
                    postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('body_system_specialty',
    sa.Column('body_system', sa.String(length=30), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
    sa.PrimaryKeyConstraint('body_system')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'model', 'tool')", name='ck_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_message_session', 'chat_message', ['session_id', 'id'], unique=False)
    op.create_table('disease_specialty',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('mapping_source', sa.String(length=20), nullable=False),
    sa.CheckConstraint("mapping_source IN ('curated', 'fallback')", name='ck_mapping_source'),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
    sa.PrimaryKeyConstraint('disease_id', 'specialty_id')
    )
    op.create_table('disease_symptom',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('support', sa.Float(), nullable=False),
    sa.CheckConstraint('support > 0 AND support <= 1', name='ck_support_range'),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_id', 'symptom_id')
    )
    op.create_index(op.f('ix_disease_symptom_symptom_id'), 'disease_symptom', ['symptom_id'], unique=False)
    op.create_table('precaution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precaution_disease_id'), 'precaution', ['disease_id'], unique=False)
    op.create_table('symptom_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_id', 'alias', name='uq_symptom_alias')
    )
    op.create_index(op.f('ix_symptom_alias_symptom_id'), 'symptom_alias', ['symptom_id'], unique=False)
    op.create_index('ix_symptom_alias_trgm', 'symptom_alias', ['alias'], unique=False, postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_symptom_alias_trgm', table_name='symptom_alias', postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_symptom_alias_symptom_id'), table_name='symptom_alias')
    op.drop_table('symptom_alias')
    op.drop_index(op.f('ix_precaution_disease_id'), table_name='precaution')
    op.drop_table('precaution')
    op.drop_index(op.f('ix_disease_symptom_symptom_id'), table_name='disease_symptom')
    op.drop_table('disease_symptom')
    op.drop_table('disease_specialty')
    op.drop_index('ix_chat_message_session', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('body_system_specialty')
    op.drop_index('ix_symptom_embedding_hnsw', table_name='symptom',
                  postgresql_using='hnsw',
                  postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_symptom_slug'), table_name='symptom')
    op.drop_index('ix_symptom_name_trgm', table_name='symptom', postgresql_using='gin', postgresql_ops={'canonical_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_symptom_body_system'), table_name='symptom')
    op.drop_table('symptom')
    op.drop_table('specialty')
    op.drop_table('red_flag')
    op.drop_index(op.f('ix_disease_slug'), table_name='disease')
    op.drop_table('disease')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
