"""drop disease_specialty.rank

Revision ID: b81511a403f0
Revises: 0a05738fa2d4
Create Date: 2026-08-02 18:35:24.633113
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b81511a403f0'
down_revision: str | None = '0a05738fa2d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disease_specialty', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # HAND-EDITED: autogenerate emitted NOT NULL with no default, which fails on a
    # populated table. server_default lets existing rows take 1.
    op.add_column('disease_specialty',
                  sa.Column('rank', sa.SMALLINT(), autoincrement=False,
                            nullable=False, server_default='1'))
    # ### end Alembic commands ###
